#Last change with swiftlint version 0.27.0
whitelist_rules:
    - class_delegate_protocol
    - closing_brace
    - colon
    - comma
    - compiler_protocol_init
    - control_statement
    - custom_rules
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - cyclomatic_complexity
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - explicit_init
    - file_length
    - force_try
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - force_cast
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - force_unwrapping
    - function_body_length
    - function_parameter_count
    - implicit_getter
    - large_tuple
    - leading_whitespace
    - legacy_cggeometry_functions
    - legacy_nsgeometry_functions
    - legacy_constant
    - legacy_constructor
    - line_length
#    - nesting
    - object_literal
    - opening_brace
    - operator_whitespace
    - overridden_super_call
#   TODO: This rule should really be enabled, but requires quite a lof changes.
#    - private_outlet
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_optional_initialization
    - redundant_string_enum_value
    - redundant_void_return
    - return_arrow_whitespace
    - statement_position
    - switch_case_on_newline
    - syntactic_sugar
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - unused_closure_parameter
    - unused_optional_binding
    - valid_ibinspectable
    - vertical_whitespace
    - weak_delegate

function_parameter_count:
    warning: 8
    error: 8
function_body_length:
    warning: 90
    error: 100
large_tuple:
    warning: 5
    error: 5

# rules that have both warning and error levels, can set just the warning level
line_length: 170
type_body_length:
  warning: 500
  error: 600
file_length:
  warning: 1800
  error: 2000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
